services:
  postgres:
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_PORT: $DB_PORT
      POSTGRES_USER: $DB_USER
    ports:
      - "$DB_PORT:$DB_PORT"
    image: docker.io/library/postgres:15.1-alpine3.16
